PUT {{apiUrl}}/v1/apply/paas
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "applicationDeploymentRefs": [
    {
      "environment": "",
      "application": "whoami"
    }
  ]
}

###