PUT {{apiUrl}}/v1/apply/paas
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "applicationDeploymentRefs": [
    {
      "environment": "utv05",
      "application": "boober"
    },
    {
      "environment": "utv05",
      "application": "gobo"
    }
  ]
}

###