POST {{apiUrl}}/v1/sts
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "referanse",
  "commonName": "no.skatteetaten.aurora.openshift.referanse",
  "namespace": "paas-sts",
  "affiliation": "paas"
}

###