PUT {{apiUrl}}/v1/auroraconfig/paas/verify-github-users/about.json
Authorization: Bearer {{token}}
Content-Type: application/json
If-Match: "ae584afdfdebe2dae1e87c506aa2c200"

{
  "content": "{\"cluster\":\"utv\"}"
}
###